# Generated by Django 4.0.3 on 2022-03-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='preco')),
            ],
        ),
    ]
