# Generated by Django 4.0.3 on 2022-03-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padarias',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
